FROM ubuntu:jammy
ENV DEBIAN_FRONTEND=noninteractive
RUN locale  # check for UTF-8

RUN apt update && apt install locales
RUN locale-gen en_US en_US.UTF-8
RUN update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
RUN export LANG=en_US.UTF-8

RUN locale 

RUN apt install -y software-properties-common
RUN add-apt-repository universe

RUN apt update && apt install curl -y
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

RUN apt update && apt install -y \
  python3-flake8-docstrings \
  python3-pip \
  python3-pytest-cov \
  ros-dev-tools

RUN apt install -y \
  python3-flake8-blind-except \
  python3-flake8-builtins \
  python3-flake8-class-newline \
  python3-flake8-comprehensions \
  python3-flake8-deprecated \
  python3-flake8-import-order \
  python3-flake8-quotes \
  python3-pytest-repeat \
  python3-pytest-rerunfailures

RUN mkdir -p /ros2_ws/src && \
cd /ros2_ws && \
vcs import --input https://raw.githubusercontent.com/ros2/ros2/humble/ros2.repos src

RUN apt upgrade -y

RUN cd /ros2_ws && rosdep init && \
rosdep update && \
rosdep install --from-paths src --ignore-src -y --skip-keys "fastcdr rti-connext-dds-6.0.1 urdfdom_headers"


RUN apt install -y gfortran




RUN cd /ros2_ws/ && colcon build --symlink-install 

RUN cd /ros2_ws/ && . /ros2_ws/install/local_setup.bash


WORKDIR /ros2_ws
#COPY ./entrypoint_talker.sh /ros2_ws/entrypoint.sh

RUN mkdir /var/lib/theconstruct.rrl
#COPY ./cyclonedds.xml /var/lib/theconstruct.rrl/

#RUN rm /etc/apt/sources.list.d/ros2.list
#RUN apt update && sudo apt install -y ros-core-dev


########### ROS1 Installation
RUN apt install -y python3-rosinstall-generator python3-vcstools python3-vcstool build-essential 
RUN add-apt-repository ppa:malcscott/ppa
RUN apt update 
RUN apt install hddtemp

RUN rosdep update

RUN mkdir -p /ros1_ws/src
RUN cd /ros1_ws && rosinstall_generator desktop --rosdistro noetic --deps --tar > noetic-desktop.rosinstall && \
vcs import --input noetic-desktop.rosinstall ./src

RUN apt install -y libpoco-dev libboost-thread-dev libboost-filesystem-dev libboost-program-options-dev liblz4-dev \
liburdfdom-headers-dev uuid-dev libbz2-dev libgpgme-dev libboost-python-dev libogre-1.9-dev liburdfdom-dev
RUN sed -e '11iset(CATKIN_ENABLE_TESTING 0)' -i /ros1_ws/src/rosconsole/CMakeLists.txt 
RUN cd /ros1_ws && ./src/catkin/bin/catkin_make_isolated -DCMAKE_BUILD_TYPE=Release
#ENTRYPOINT ["/bin/bash", "-c", "/ros2_ws/entrypoint.sh"]

# Create a workspace for the ros1_bridge
RUN mkdir -p /ros1_bridge/src
RUN cd /ros1_bridge/src && git clone https://github.com/ros2/ros1_bridge
RUN cd /ros1_bridge && . /ros2_ws/install/local_setup.bash

# Build
RUN apt-get install -y ros-humble-rmw-implementation ros-humble-rmw-implementation-cmake ros-humble-rclcpp
####### .bashrc 
RUN cd /ros2_ws && touch .bashrc && echo "export ROS1_INSTALL_PATH=/ros1_ws/devel_isolated" >> .bashrc && echo "export ROS2_INSTALL_PATH=/opt/ros/humble" >> .bashrc
# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]
ENV ROS1_INSTALL_PATH=/ros1_ws/devel_isolated
ENV ROS2_INSTALL_PATH=/ros2_ws/install
RUN apt install -y ros-humble-ament-lint-auto
RUN cd /ros1_bridge && source ${ROS1_INSTALL_PATH}/setup.bash && source ${ROS2_INSTALL_PATH}/setup.bash && \
colcon build --symlink-install --packages-select ros1_bridge --cmake-force-configure

RUN apt-get install python3-defusedxml



CMD ["/bin/bash"]
